openapi: 3.0.3
info:
    title: OpenWeather
    description: openweathermap.org
    version: 1.0.0
servers:
- url: https://api.openweathermap.org/data/2.5
tags:
- name: weather
  description: weather info
paths:
    /weather/:
      get:
        tags:
        - weather
        summary: City weather info
        operationId: fetchWeatherData
        parameters:
        - name: q
          in: query
          description: City name
          required: true
          schema:
            type: string
        - name: appid
          in: query
          description: API key
          required: true
          schema:
            type: string
        - name: lang
          in: query
          description: Language
          required: false
          schema:
            type: string
        responses:
            "200":
              description: success
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/WeatherData'
            default:
              description: enexpected error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    WeatherData:
        type: object
        properties:
            coord:
                type: object
                properties:
                    lon:
                      type: number
                    lat:
                      type: number
            weather:
              type: array
              items:
                $ref: '#/components/schemas/Weather'
            base:
                type: string
            main:
              $ref: '#/components/schemas/WeatherTempData'
            visibility:
              type: integer
            wind:
                type: object
                properties:
                    speed:
                      type: integer
                    deg:
                      type: integer
            clouds:
                type: object
                properties:
                    all:
                      type: integer
            dt:
                type: integer
            sys:
                type: object
                properties:
                    type:
                        type: integer
                    id:
                        type: integer
                    country:
                        type: string
                    sunrise:
                        type: integer
                    sunset:
                        type: integer
            timezone:
                type: integer
            id:
                type: integer
            name:
                type: string
            cod:
                type: integer
    ErrorModel:
        required:
        - code
        - message
        type: object
        properties:
          message:
            type: string
          code:
            maximum: 600
            minimum: 100
            type: integer
    WeatherTempData:
        required:
        - temp
        - feels_like
        - temp_min
        - temp_max
        - pressure
        - humidity
        type: object
        properties:
         temp:
            type: number
         feels_like:
            type: number
         temp_min:
            type: number
         temp_max:
            type: number
         pressure:
            type: number
         humidity:
            type: number
    Weather:
        required:
        - id
        type: object
        properties:
            id:
                type: integer
            main:
                type: string
            description:
                type: string
            icon:
                type: string
